source = $HOME/.config/hypr/macchiato.conf
$mainMonitor = DP-5

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = JetBrainsMono Nerd Font

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
}

# BACKGROUND
background {
  monitor = 
  path = $HOME/.config/images/desktop/ultrawide_island.png
  blur_passes = 0
  color = $base
}

# TIME
label {
  monitor = $mainMonitor
  text = $TIME
  color = $overlay2
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor = $mainMonitor
  text = cmd[update:43200000] date +"%A %d.%m.%Y"
  color = $overlay2
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

# INPUT FIELD
input-field {
  monitor = $mainMonitor
  size = 350, 60
  outline_thickness = 2
  dots_size = 0.15
  dots_spacing = 0.22
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -210
  halign = center
  valign = center
}
